ARG PHP_VERSION

FROM $PHP_VERSION

#RUN apt-get update && apt-get install -y libicu-dev \
#    && docker-php-ext-configure intl \
#    && docker-php-ext-install pdo pdo_mysql intl


RUN apt-get update && apt-get install -y \
      libicu-dev \
      libpq-dev \
      zlib1g-dev \
      libzip-dev \
      libmcrypt-dev \
      #mysql-client \
      git \
      zip \
      unzip \
    && rm -r /var/lib/apt/lists/* \
    && docker-php-ext-configure pdo_mysql --with-pdo-mysql=mysqlnd \
    && docker-php-ext-install \
      intl \
      mbstring \
      #mcrypt \
      pcntl \
      pdo_mysql \
      pdo_pgsql \
      pgsql \
      zip \
      opcache

#install composer
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/bin/ --filename=composer
