ARG PHP_VERSION

FROM $PHP_VERSION


RUN apt-get update && apt-get install -y libicu-dev \
    && docker-php-ext-configure intl \
    && docker-php-ext-install pdo pdo_mysql intl


#php zip, intel ...
